openapi: 3.0.3
info:
  title: Credit Card Available Funds_Retrieve
  version: 1.0.0
  description: Use this API to retrieve card available funds details
  x-generated-by: SOR Polymorphizer 6.8
  x-generated-at: '2026-09-11T05:20:33+00:00'
  x-source-sheet: Available Funds_Retrieve
  x-polymorphism-pattern: P1
  x-bian-service-domain: Credit Card
paths:
  /credit-card/financial-status-tracking/retrieve:
    post:
      operationId: availableFundsRetrieve
      summary: Available Funds Retrieve API
      tags:
      - Credit Card
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialStatusTrackingResponse'
          headers:
            x-BDO-Client-Request-Id:
              $ref: '#/components/headers/x-BDO-Client-Request-Id'
            x-BDO-Client-Request-Trace-Id:
              $ref: '#/components/headers/x-BDO-Client-Request-Trace-Id'
            x-BDO-Client-Request-Span-Id:
              $ref: '#/components/headers/x-BDO-Client-Request-Span-Id'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '502':
          $ref: '#/components/responses/BadGateway'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FinancialStatusTrackingRequest'
      description: "**<u>API Lifecycle Status - Design</u>**\n\nUse this API to retrieve card available
        funds details"
      x-api-lifecycle-status: Design
      x-use-case: Use this API to retrieve card available funds details
      x-bian-behaviour-qualifier: Financial Status Tracking
      x-sor-endpoints: /v1/card/availableFunds
components:
  schemas:
    FinancialStatusTrackingRequest:
      type: object
      properties:
        IssuedDeviceIdentifier:
          type: object
          properties:
            issuedDeviceIdentification:
              type: string
              maxLength: 19
              description: Identifier representing the issued device.
              example: '5111222233334440'
              x-sor-field: cardNumber
          required:
          - issuedDeviceIdentification
        CurrencyCode:
          type: string
          maxLength: 3
          description: Currency Code
          example: PHP
          x-sor-field: currencyCode
      x-class: FinancialStatusTrackingRequest
      x-qualified-name: FinancialStatusTrackingRequest
    FinancialStatusTrackingResponse:
      type: object
      properties:
        CustomerReference:
          type: object
          properties:
            PartyIdentifier:
              type: object
              properties:
                partyIdentification:
                  type: string
                  description: Unique identifier value representing the customer.
                  example: '0014308593'
                  x-sor-field: customerNumber
              description: Reference to the associated party.
          description: Represents a person or organization that participates in a business 
            relationship with the institution.
        CustomerLimit:
          type: object
          properties:
            limitValue:
              type: string
              description: "Value of Limit.\nWhen LimitType = CustomerLimit,\nLimitValue = Overall limit
                of customer"
              example: '10000'
              x-sor-field: customerLimit
            limitCurrencyCode:
              type: string
              description: Identifies the currency in which the limit value is expressed.
              example: PHP
              x-sor-field: customerLimitCurrency
          description: Object used to identify type of limit on card, limit value and limit 
            currency.
        IssuedDeviceStatus:
          type: object
          properties:
            primaryCardTag:
              type: string
              description: "The primary card status of the card.\nPossible Values:\nFirst Primary,\nOther
                Primary,\nFirst Supplementary,\nOther Supplementary,"
              example: First Primary
              x-sor-field: primary
            deviceStatusCode:
              type: string
              description: Value of card cancellation code.
              example: L
              x-sor-field: cancelCode
          description: Object used to identify type of card and card details.
        AccountInformation:
          type: array
          items:
            type: object
            properties:
              accountCurrencyCode:
                type: string
                description: Currency code for the account.
                example: PHP
                x-sor-field: accountInfo.currency
              accountCloseCode:
                type: string
                description: Account Close code
                example: C
                x-sor-field: accountInfo.closeCode
              CardLimit:
                type: object
                properties:
                  limitValue:
                    type: string
                    description: "Value of Limit.\nWhen LimitType = CreditLimit, LimitValue = Credit limit
                      set for the account\nWhen LimitType = LimitCash, LimitValue = Cash limit calculated
                      as percentage of Credit Limit.\nWhen LimitType = MonthlyLimit, LimitValue = The
                      current monthly spend limit for the combination of card and account."
                    example: '10000'
                    x-sor-field: accountInfo.limit accountInfo.limitCash 
                      accountInfo.cardSpending.monthlyLimit
              AccountLimitUtilized:
                type: object
                properties:
                  amountValue:
                    type: string
                    description: Amount Spent on the account for current month. The field is 
                      provided when monthly spending limit is set for the card (not 0).
                    example: '15000.00'
                    x-sor-field: accountInfo.cardSpending.spentThisMonth
                description: Amount and currency of limit utilized for the month.
              AccountBalance:
                type: array
                items:
                  type: object
                  properties:
                    balanceAmount:
                      type: string
                      description: "Value of amount.\nNote:\nWhen BalanceType = Purchase, BalanceAmount
                        = Available Amount for purchases\nWhen BalanceType = CashAdvance, BalanceAmount
                        = Available Amount for cash advances\nWhen BalanceType = MajorPurchase, BalanceAmount
                        = Available Amount for major purchases"
                      example: '15000.00'
                      x-sor-field: accountInfo.cardAvailable.purchase 
                        accountInfo.cardAvailable.cashAdvance 
                        accountInfo.cardAvailable.majorPurchase
                description: Object used to identify type of amount, value of amount and currency.
              LastPayment:
                type: object
                properties:
                  paymentAmount:
                    type: string
                    description: Last payment amount
                    example: '100.12'
                    x-sor-field: accountInfo.lastPaymentAmount
                  paymentDate:
                    type: string
                    format: date-time
                    description: Date of the last payment
                    example: 2021-08-01 14:20:10:95
                    x-sor-field: accountInfo.lastPaymentDate
          description: Account details.
      x-class: FinancialStatusTrackingResponse
      x-qualified-name: FinancialStatusTrackingResponse
    ErrorResponse:
      description: An array of detail error codes, and messages, and URLs to documentation to help 
        remediation.
      type: object
      properties:
        status:
          type: string
          description: The HTTP status code of the response
        title:
          type: string
          description: A short, human-readable summary of the error.
        timestamp:
          type: string
          format: date-time
          description: A standardized date and time format defined by the ISO 8601 standard
        errors:
          type: array
          description: Array of errors within an object to provide additional information.
          items:
            type: object
            properties:
              realm:
                type: string
                description: Indicates the architectural layer or system component where the error 
                  originated.
              code:
                type: string
                description: Represents a unique identifier for the specific error condition.
              errordesc:
                type: string
                description: Provides a short, human-readable description of the error associated 
                  with the code.
              detail:
                type: string
                description: A more comprehensive explanation of the error, including what went 
                  wrong and how to fix it.
              instance:
                type: string
                description: A URI that identifies the specific occurrence of the problem.
      example:
        status: '400'
        title: Bad Request
        timestamp: '2026-07-14T08:16:49.876Z'
        errors:
        - realm: Apigee
          code: '001'
          errordesc: QUERY_PARAMETER_FAILURE
          detail: The input query parameters do not match the open api spec
          instance: /v1/<resource>/<action>
      x-class: ErrorResponse
      x-qualified-name: ErrorResponse
  headers:
    x-BDO-Client-Request-Id:
      schema:
        type: string
      description: The unique id (preferable uuidv4) provided by the client for a specific HTTP 
        request.
    x-BDO-Client-Request-Trace-Id:
      schema:
        type: string
      description: The unique identifier for an entire trace in OpenTelemetry (OTEL). A trace 
        represents a single request or transaction as it flows through multiple services in a 
        distributed system.
    x-BDO-Client-Request-Span-Id:
      schema:
        type: string
      description: Uniquely identifies a single span within a trace. A span represents one unit of 
        work, for example an HTTP request or a database query.
  responses:
    BadRequest:
      description: "Bad Request\n\nDisclaimer: The error message is Apigee error only and not mapped to
        the System API error. Consumers should not rely on the exact error text as it may change depends
        on the format of the System API its calling."
      headers:
        x-BDO-Client-Request-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Id'
        x-BDO-Client-Request-Trace-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Trace-Id'
        x-BDO-Client-Request-Span-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Span-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: "Unauthorized\n\nDisclaimer: The error message is Apigee error only and not mapped
        to the System API error. Consumers should not rely on the exact error text as it may change depends
        on the format of the System API its calling."
      headers:
        x-BDO-Client-Request-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Id'
        x-BDO-Client-Request-Trace-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Trace-Id'
        x-BDO-Client-Request-Span-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Span-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Forbidden:
      description: "Forbidden\n\nDisclaimer: The error message is Apigee error only and not mapped to
        the System API error. Consumers should not rely on the exact error text as it may change depends
        on the format of the System API its calling."
      headers:
        x-BDO-Client-Request-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Id'
        x-BDO-Client-Request-Trace-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Trace-Id'
        x-BDO-Client-Request-Span-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Span-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: "Not Found\n\nDisclaimer: The error message is Apigee error only and not mapped to
        the System API error. Consumers should not rely on the exact error text as it may change depends
        on the format of the System API its calling."
      headers:
        x-BDO-Client-Request-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Id'
        x-BDO-Client-Request-Trace-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Trace-Id'
        x-BDO-Client-Request-Span-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Span-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    MethodNotAllowed:
      description: "Method Not Allowed\n\nDisclaimer: The error message is Apigee error only and not mapped
        to the System API error. Consumers should not rely on the exact error text as it may change depends
        on the format of the System API its calling."
      headers:
        x-BDO-Client-Request-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Id'
        x-BDO-Client-Request-Trace-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Trace-Id'
        x-BDO-Client-Request-Span-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Span-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Conflict:
      description: "Conflict\n\nDisclaimer: The error message is Apigee error only and not mapped to the
        System API error. Consumers should not rely on the exact error text as it may change depends on
        the format of the System API its calling."
      headers:
        x-BDO-Client-Request-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Id'
        x-BDO-Client-Request-Trace-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Trace-Id'
        x-BDO-Client-Request-Span-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Span-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    UnprocessableEntity:
      description: "Unprocessable Entity\n\nDisclaimer: The error message is Apigee error only and not
        mapped to the System API error. Consumers should not rely on the exact error text as it may change
        depends on the format of the System API its calling."
      headers:
        x-BDO-Client-Request-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Id'
        x-BDO-Client-Request-Trace-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Trace-Id'
        x-BDO-Client-Request-Span-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Span-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    TooManyRequests:
      description: "Too Many Requests\n\nDisclaimer: The error message is Apigee error only and not mapped
        to the System API error. Consumers should not rely on the exact error text as it may change depends
        on the format of the System API its calling."
      headers:
        x-BDO-Client-Request-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Id'
        x-BDO-Client-Request-Trace-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Trace-Id'
        x-BDO-Client-Request-Span-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Span-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: "Internal Server Error\n\nDisclaimer: The error message is Apigee error only and not
        mapped to the System API error. Consumers should not rely on the exact error text as it may change
        depends on the format of the System API its calling."
      headers:
        x-BDO-Client-Request-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Id'
        x-BDO-Client-Request-Trace-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Trace-Id'
        x-BDO-Client-Request-Span-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Span-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    BadGateway:
      description: "Bad Gateway\n\nDisclaimer: The error message is Apigee error only and not mapped to
        the System API error. Consumers should not rely on the exact error text as it may change depends
        on the format of the System API its calling."
      headers:
        x-BDO-Client-Request-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Id'
        x-BDO-Client-Request-Trace-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Trace-Id'
        x-BDO-Client-Request-Span-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Span-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ServiceUnavailable:
      description: "Service Unavailable\n\nDisclaimer: The error message is Apigee error only and not
        mapped to the System API error. Consumers should not rely on the exact error text as it may change
        depends on the format of the System API its calling."
      headers:
        x-BDO-Client-Request-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Id'
        x-BDO-Client-Request-Trace-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Trace-Id'
        x-BDO-Client-Request-Span-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Span-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    GatewayTimeout:
      description: "Gateway Timeout\n\nDisclaimer: The error message is Apigee error only and not mapped
        to the System API error. Consumers should not rely on the exact error text as it may change depends
        on the format of the System API its calling."
      headers:
        x-BDO-Client-Request-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Id'
        x-BDO-Client-Request-Trace-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Trace-Id'
        x-BDO-Client-Request-Span-Id:
          $ref: '#/components/headers/x-BDO-Client-Request-Span-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
