openapi: 3.0.3
info:
  title: Credit Card Card RSAEncrypted
  version: 1.0.0
  description: This API will be used to get the card number encrypted, the expiry date, and 
    optionally the CVV2. Encryption is made via a Public RSA key base64 encoded in format X.509.
  x-generated-by: SOR Polymorphizer 6.4
  x-generated-at: '2026-09-09T02:20:54+00:00'
  x-source-sheet: Card RSAEncrypted
  x-polymorphism-pattern: P1
  x-bian-service-domain: Credit Card
paths:
  /credit-card/issued-device/card-rsa-encrypted/retrieve:
    post:
      operationId: cardRSAEncrypted
      summary: This API will be used to get the card number encrypted, the expiry date, and 
        optionally the CVV2. Encryption is made via
      tags:
      - Credit Card
      responses:
        '204':
          description: 'Successful. This operation returns no content: the Response Body section of the
            mapping workbook carries no attribute mapped to an SOR field.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssuedDeviceCardEncryptedRequest'
      description: This API will be used to get the card number encrypted, the expiry date, and 
        optionally the CVV2. Encryption is made via a Public RSA key base64 encoded in format X.509.
      x-bian-behaviour-qualifier: Issued Device
      x-bian-equivalent-endpoint: /credit-card/issued-device/card-rsa-encrypted/retrieve
      x-sor-endpoints: GET /v1/card/{cardNumber}/cardRSAEncrypted
components:
  schemas:
    IssuedDeviceCardEncryptedRequest:
      type: object
      properties:
        IssuedDeviceIdentifier:
          type: object
          properties:
            issueddeviceIdentification:
              type: string
              description: The card number or card token number generated by Vertexon CMS
              x-sor-field: cardNumber
          required:
          - issueddeviceIdentification
