openapi: 3.0.3
info:
  title: Credit Card Customer Addl Data
  version: 2.0.0
  description: This API will be used to get the customer additional data for specified customer 
    number or card number
  x-generated-by: SOR Polymorphizer 6.3
  x-generated-at: '2026-09-02T20:53:50+00:00'
  x-source-sheet: Customer Addl Data
  x-polymorphism-pattern: P1
  x-bian-service-domain: Credit Card
paths:
  /credit-card/customer/additional-data/retrieve:
    post:
      operationId: customerAddlData
      summary: This API will be used to get the customer additional data for specified customer 
        number or card number
      tags:
      - Credit Card
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardCustomerAdditionalDataResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardCustomerAdditionalDataRequest'
      description: This API will be used to get the customer additional data for specified customer 
        number or card number
      x-bian-behaviour-qualifier: '- Additional Data'
      x-bian-equivalent-endpoint: /credit-card/customer/additional-data/retrieve
      x-sor-endpoints: GET /v1/customer/additionalData
components:
  schemas:
    CardCustomerAdditionalDataRequest:
      type: object
      properties:
        PartyIdentifier:
          type: object
          properties:
            partyIdentification:
              type: string
              description: customer number
              example: '10000001'
              x-sor-field: customerNumber
        IssuedDeviceIdentifier:
          type: object
          properties:
            issueddeviceIdentification:
              type: string
              description: The card number or card token number generated by Vertexon CMS
              example: '5555000012348870'
              x-sor-field: cardNumber
        searchCodes:
          type: string
          description: Search filter - array of 4 digit codes or use code [ALL] to request for all 
            available data.
          example: 0700,0800
          x-sor-field: codes
      required:
      - searchCodes
    CardCustomerAdditionalDataResponse:
      type: object
      properties:
        CustomerAdditionalData:
          type: array
          items:
            type: object
            properties:
              searchCode:
                type: string
                description: code type
                example: ADCUS
                x-sor-field: customerData.code
              description:
                type: string
                description: The system description of the code
                example: Additional Data1
                x-sor-field: customerData.description
              value:
                type: string
                description: code value
                example: SYSTM
                x-sor-field: customerData.value
          description: It specifies the customer additional data
          x-sor-fields:
            /v1/customer/additionalData: customerData
