openapi: 3.0.3
info:
  title: Credit Card Card Cancel
  version: 2.0.0
  description: This API will be used to cancel a card with specified reason or cancellation code
  x-generated-by: SOR Polymorphizer 6.0
  x-generated-at: '2026-09-02T13:10:38+00:00'
  x-source-sheet: Card Cancel
  x-polymorphism-pattern: P1
  x-bian-service-domain: Credit Card
paths:
  /credit-card/issued-device/control:
    put:
      operationId: cardCancel
      summary: This API will be used to cancel a card with specified reason or cancellation code
      tags:
      - Credit Card
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditCardCancelRequest'
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardCancelResponse'
      description: This API will be used to cancel a card with specified reason or cancellation code
      x-bian-behaviour-qualifier: Issued Device
      x-bian-equivalent-endpoint: /credit-card/issued-device/control
      x-sor-endpoints: PUT /v1/card/cancel
components:
  schemas:
    CreditCardCancelRequest:
      type: object
      properties:
        IssuedDeviceIdentifier:
          type: object
          properties:
            issueddeviceIdentification:
              type: string
              example: '5555000012348870'
              x-sor-field: cardNumber
        cancelCode:
          type: string
          maxLength: 1
          description: Reason why the card is to be cancelled
          example: L
          x-sor-field: cancelCode
        cancelNotes:
          type: string
          maxLength: 350
          description: "Customer report that card was lost in a travel,\nFree-flow entry field, used to
            enter notes related to card cancellation"
          x-sor-field: cancelNotes
        CancelReportDetails:
          type: object
          properties:
            reportDate:
              type: string
              format: date
              maxLength: 10
              description: The customer reported date, E.g. if the card has been lost, the date of 
                loss.
              x-sor-field: reportDetails.reportDate
            reportTime:
              type: string
              maxLength: 5
              description: The customer reported time in format HH:MM, E.g. if the card has been 
                lost, the time of loss.
              example: 14:00:00
              x-sor-field: reportDetails.reportTime
            reportMethod:
              type: string
              maxLength: 3
              description: The method used to report the loss/stolen. To obtain the possible values 
                in the system
              example: PHN
              x-sor-field: reportDetails.reportMethod
            dateLastSeen:
              type: string
              format: date
              maxLength: 10
              description: The date reported by customer when card was last seen.
              x-sor-field: reportDetails.reportDateLastSeen
            placeLastSeen:
              type: string
              maxLength: 100
              description: The place reported by customer where card was last seen.
              example: N.Y Central Park
              x-sor-field: reportDetails.reportDatePlaceLastSeen
            reportedBy:
              type: string
              maxLength: 100
              description: The person who reported the issue. Only required if the place the card 
                was last seen is specified.
              example: Mr.Anderson
              x-sor-field: reportDetails.reportedBy
          description: "\nCancellation report details should be sent if required by the specified cancel
            code, e.g. if the card is lost or stolen"
      required:
      - cancelCode
      - cancelNotes
      description: The details of the card cancellation request
    CreditCardCancelResponse:
      type: object
      properties:
        IssuedDeviceIdentifier:
          type: object
          properties:
            issueddeviceIdentification:
              type: string
              description: The token generated by Vertexon CMS to represent the real card number. 
                Must start with 1 and be 17 length.
              example: '15555000000002500'
              x-sor-field: cardToken
            issueddeviceIdentificationMasked:
              type: string
              description: The masked card number. Middle characters are replaced with '*'.
              example: 5555 55** **** 1234
              x-sor-field: cardNumberMasked
        Status:
          type: object
          properties:
            statusEffectiveDate:
              type: string
              format: date
              description: The date on which the card status was changed,
              example: 14:20:10
              x-sor-field: statusDate
            statusEffectiveTime:
              type: string
              description: The time when the card status was changed
              x-sor-field: statusTime
        referenceNumber:
          type: string
          description: Unique reference number generated by the system. Only returned in the 
            response only when the cancellation code requires a reference. This property is not 
            present when reactivating a cancelled card or when the cancellation code does not 
            require a reference.
          example: '0001234'
          x-sor-field: referenceNbr
